apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init-chapter
  namespace: argocd
  annotations:
    "helm.sh/resource-policy": keep
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bitbucket.org/repo/repo
    targetRevision: release
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
