# Longhorn Clean Production Values
persistence:
  # Número de réplicas para cada volume (3 = alta disponibilidade)
  defaultClassReplicaCount: 2
  
  # Política de retenção - mantém dados mesmo se PVC for deletado
  reclaimPolicy: Retain

defaultSettings:
  # Remove snapshots automaticamente durante trim do filesystem
  removeSnapshotsDuringFilesystemTrim: enabled
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 15
  autoCleanupSystemGeneratedSnapshot: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  orphanAutoDeletion: true

  # NOVO: Reduz overhead de metadados e melhora performance
  concurrentAutomaticEngineUpgradePerNodeLimit: 1
  # # Caminho onde o Longhorn armazena os dados nos nós
  # defaultDataPath: "/opt/longhorn"
  
  # Balanceamento automático de réplicas entre nós
  replicaAutoBalance: best-effort
# isso faz com que o Longhorn tente balancear as réplicas entre os nós, mas não é obrigatório mas isso pode ajudar a evitar problemas de performance se um nó ficar sobrecarregado
  # e não afeta a disponibilidade do volume
  # Configuração de balanceamento automático de réplicas do Longhorn pod mesmo ser útil em ambientes com nós heterogêneos, onde alguns nós podem ter mais recursos disponíveis que outros.
  # Isso ajuda a distribuir a carga de trabalho de forma mais equilibrada entre os nós, melhorando a performance geral do cluster. ma isso é do pod ou volume
  # Configuração de balanceamento automático de réplicas do Longhorn pode ser útil em ambientes com nós heterogêneos, onde alguns nós podem ter mais recursos disponíveis que outros.
  # Isso ajuda a distribuir a carga de trabalho de forma mais equilibrada entre os nós, melhorando a performance geral do cluster. o que extamten issofaz? 
  
  
  # Recuperação automática de volumes com problemas
  autoSalvage: true

  # NOVO: Reduz uso de CPU/Memory dos componentes
  upgradeChecker: false
  
  # Desabilita snapshots automáticos
  recurringJobSelector: ""
  snapshotDataIntegrity: disabled
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: false
  systemManagedPodsImagePullPolicy: IfNotPresent

longhornUI:
  # Réplicas da UI - pode ser reduzido para 1 se não precisar de HA
  replicas: 1

# CONFIGURAÇÕES ADICIONAIS para ambiente limitado
ingress:
  # Desabilita ingress se não precisar de acesso externo
  enabled: false

service:
  ui:
    # Usa NodePort se precisar de acesso, mais leve que LoadBalancer
    type: NodePort

    # CSI Driver com réplicas balanceadas (economia + disponibilidade)
csi:
  attacherReplicaCount: 2     # Padrão: 3 (crítico para anexar volumes)
  provisionerReplicaCount: 2  # Padrão: 3 (importante para criar volumes)
  resizerReplicaCount: 2      # Padrão: 3 (resize de volumes)
  snapshotterReplicaCount: 0  # Padrão: 3 (desativado - não usa snapshots)