apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: external-secret-argocd-helm
spec:
  namespaces:
    - argocd
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend-external
      kind: ClusterSecretStore 
    refreshInterval: "2m"
    target:
      name: helm-repo  # Nome da sACecret que o ArgoCD reconhecerá
      creationPolicy: 'Owner'
      template:
        metadata:
          labels:  # Adicionando as labels necessárias para o ArgoCD reconhecer como secret de repositório
            app.kubernetes.io/instance: argocd
            app.kubernetes.io/part-of: argocd
            argocd.argoproj.io/secret-type: repository
    dataFrom:
      - extract:
          key: argocd/helm-repo